### ISSUE TITLE
how to extract eta values from fit results

### ISSUE THREAD

**Issue by mark0935git** [PumasAI/PumasDocs.jl#98]
In the current docs, I have not found how to extrac individual eta values of estimated PK parameters from the fit results.
Could you please instruct me how I can extract the eta value?
Thanks.

**Comment by vjd** [comment]
Thanks for pointing out, Marc. This detail has been added in the development version and will updated soon. 
In the meantime, you could do `?icoef` in the REPL after Pumas is loaded and you should get this

```julia

  icoef(fpm::FittedPumasModel)::Vector{ConstantInterpolationStructArray}

  Return the individual coefficients from fpm. The individual coefficients are the variables defined in the @pre block in the @model macro. The function return a
  vector of covariate interpolation objects. Each of which can be evaluated at any time point. Each of the covariate interpolation objects can be converted to a
  DataFrame by calling the DataFrame constructor. Hence, a complete DataFrame of the individual coefficients can be obtained by calling reduce(vcat,
  DataFrame.(icoef(fpm))).
```

`coef` is used to get  _Population parameters_ and `icoef` is used to get the individual parameters. When you have a `fit`, you access the individual parameters by calling `reduce(vcat,  DataFrame.(icoef(myfit)))`

**Comment by mark0935git** [comment]
@vjd thank you very much for your explanation! It solves my questions.
