### ISSUE TITLE
how to extract individual and population predicted PK profiles from fit result

### ISSUE THREAD

**Issue by mark0935git** [PumasAI/PumasDocs.jl#99]
I have not found in the pumas docs whether it is feasbile to extract individual and population predicted PK profiles (IPRED and PRED) from fit results, as it is in Phenoix?

**Comment by vjd** [comment]
Hi @mark0935git 

The `inspect` function does three things  and is documented [here](https://docs.pumas.ai/stable/analysis/diagnostics/#The-inspect-Function)
1. `predict` population and individual predictions
2. `wresiduals` provide method appropriate weighted residuals and individual weighted residuals
3. `empirical_bayes` provides the EBE's

So, if you have a `fit` result such as `myfit = fit(mymodel, population, parameters, Pumas.FOCEI()`, then you have to do 
`DataFrame(inspect(myfit))` to get you dataframe of predictions.

Also, please checkout the introduction tutorial [here](https://tutorials.pumas.ai/html/introduction/introduction.html) to look at the entire workflow.

**Comment by mark0935git** [comment]
@vjd Thank you for your help! It is very helpful!
